module.exports = {
  content: ['./src/**/*.{html,ts}'],
  theme: {
    extend: {
      colors: {
        'gestor-primaria': 'rgb(var(--gestor-primaria-rgb) / <alpha-value>)',
        'gestor-primaria-hover': 'rgb(var(--gestor-primaria-hover-rgb) / <alpha-value>)',
        'gestor-primaria-ativa': 'rgb(var(--gestor-primaria-ativa-rgb) / <alpha-value>)',
        'gestor-fundo': 'rgb(var(--gestor-fundo-rgb) / <alpha-value>)',
        'gestor-superficie': 'rgb(var(--gestor-superficie-rgb) / <alpha-value>)',
        'gestor-elevada': 'rgb(var(--gestor-elevada-rgb) / <alpha-value>)',
        'gestor-sutil': 'rgb(var(--gestor-sutil-rgb) / <alpha-value>)',
        'gestor-borda': 'rgb(var(--gestor-borda-rgb) / <alpha-value>)',
        'gestor-borda-forte': 'rgb(var(--gestor-borda-forte-rgb) / <alpha-value>)',
        'gestor-texto-principal': 'rgb(var(--gestor-texto-principal-rgb) / <alpha-value>)',
        'gestor-texto-secundario': 'rgb(var(--gestor-texto-secundario-rgb) / <alpha-value>)',
        'gestor-texto-terciario': 'rgb(var(--gestor-texto-terciario-rgb) / <alpha-value>)',
        'gestor-texto-suave': 'rgb(var(--gestor-texto-suave-rgb) / <alpha-value>)',
        fundo: 'rgb(var(--cor-fundo-rgb) / <alpha-value>)',
        superficie: 'rgb(var(--cor-superficie-rgb) / <alpha-value>)',
        'superficie-secundaria': 'rgb(var(--cor-superficie-secundaria-rgb) / <alpha-value>)',
        borda: 'rgb(var(--cor-borda-rgb) / <alpha-value>)',
        primaria: 'rgb(var(--cor-primaria-rgb) / <alpha-value>)',
        'primaria-hover': 'rgb(var(--cor-primaria-hover-rgb) / <alpha-value>)',
        'primaria-ativa': 'rgb(var(--cor-primaria-ativa-rgb) / <alpha-value>)',
        'cor-texto': 'rgb(var(--cor-texto-rgb) / <alpha-value>)',
        'cor-texto-secundaria': 'rgb(var(--cor-texto-secundaria-rgb) / <alpha-value>)',
        'cor-texto-terciaria': 'rgb(var(--cor-texto-terciaria-rgb) / <alpha-value>)',
        'cor-texto-suave': 'rgb(var(--cor-texto-suave-rgb) / <alpha-value>)',
      },
    },
  },
  plugins: [],
};
